### ISSUE TITLE
As a developer, I want a wiki for Test-Driven Development / TestCafe / Testing Repo (Share with the whole team)

### ISSUE THREAD

**Issue by nevantan** [ccswbs/testing#36]
@mmafe commented on [Mon Jun 05 2017](https://github.com/ccswbs/aoda-tasks/issues/94)

Detailed documentation on development and usage of the test suite.

The test suite is comprised of three components: internal utilities, writing tests, and using the suite. This task covers the first two components; the third will be documented as a separate task.

- [ ] Extending the test suite
- [ ] Feature files
- [ ] Ava tests
- [ ] Reorganize existing content
- [ ] Notes on Testcafe API
- [ ] Scenario prefix keywords
- [ ] include workflow for developers getting started
- [ ] Add a Troubleshooting page with common errors
   - `Error: Cannot find module '<insert module name here>'`: Re-run `npm install` and `npm install --only=dev` prior to running tests. You will need to do this when new modules have been installed which are not tracked by version control.
- [ ] Must enable UG Testing API feature on Drupal site
- [ ] Release workflow, two branches to match hjckrrh releases
- [ ] Instructions + naming consistency for running tests using different roles (e.g. author, editor, sitemanager, etc.)

**Comment by nevantan** [comment]
# [WIP] Wiki Outline: Running Tests
- Installation
    - Installing Node
    - The Testing Repo
         - Description of branches
    - Installing Modules
         - `npm install` and `npm install --only=dev`
         - Why?
         - Investigate using commands (e.g. Ben's issue)
    - Testcafe global install: `npm install -g testcafe`, may need sudo
         - Why?
- Environment File
    - Rename file from environment.js to .env
    - implement node env to auto-load the .env file
    - update .gitignore with new file name
- Running a Test
    - `testcafe` command details
    - test file locations
- Setting up a test site
    - Must be a fresh clone of hjckrrh
    - Must be installed through either the web UI or drush
    - Must have ug_testing_api uninstalled
- Test Running Troubleshooting
    - Large wall of red HTML content
         - The markup is our theme's 404 page
         - FIX: Install/enable ug_testing_api feature on test site
    - [404 invalid node type]
         - Check Actions.CreateNode args and ensure it matches new method signature
         - Check spelling of node name, case-sensitive
              - Must match machine name of content type
         - Ensure the content type exists, book nodes are a good example of needing the book module enabled else this error will be thrown

**Comment by nevantan** [comment]
# [WIP] Wiki Outline: Extending the Test Suite
- Introduction
   - Project directory overview
   - Why/When would you use this section
- Ava
- Local Modules
   - Why local modules
   - Creating/Modifying modules
   - Detail individual modules

**Comment by nevantan** [comment]
# [WIP] Wiki Outline: Writing Tests

**Comment by mmafe** [comment]
@nevantan How about a section on tapping into the Drupal Services API? (Note: if you already have this covered, never mind. :))

**Comment by mmafe** [comment]
**Update:** We are going to:
- Add a Table of Contents
- Remove the scary Warning text
